# ---------------------------------- #
#      LavMusicBot Config            #
# ---------------------------------- #

# Your discord bot token, get it from https://discord.com/developers/applications
discord-bot-token: "YOUR_TOKEN_HERE"

# The default volume of the bot when it starts playing in a new server.
# Value must be between 1 and 100.
default-volume: 10

# --- Lavalink Config ---

using-nodes-json-file: false # Set this to true if you are using a nodes.json file, if you want to use the bottom config, set this to false
nodes-json-file: "C:\\path\\to\\nodes.json" # The path to your nodes.json file

# --- Lavalink Server Details (Only if you're not using a nodes.json file) ---
# Get these from your Lavalink provider or your own server.
# A list of public servers can be found at https://lavalink-list.appujet.site/

# The hostname or IP address of the Lavalink server.
lavalink-host: "lavalink.example.com"

# The port the Lavalink server is running on.
lavalink-port: 2000

# Set to 'true' if your Lavalink server uses a secure (SSL/TLS) connection.
lavalink-secure: false

# The password for your Lavalink server.
lavalink-password: "pleaseletmein"

# --- Permissions ---

# Set this to true if you want to enable permissions
permissions-enabled: false

# Set this to true if you want to use a blacklist instead of a whitelist
whitelist-acts-as-blacklist: false

# The role IDs of the roles you want to allow to use the bot
role-id-whitelist:
  - "123123123"
  - "456456456"


# --- Do Not Edit Below This Line ---
version: "${project.version}"